namespace SAIN.Preset.Shared.Enums;

public enum EBrain
{
    ArenaFighter,
    BossBully,
    BossGluhar,
    BossBoar,
    BossPartisan,
    Knight,
    BossKojaniy,
    BossSanitar,
    BossKolontay,
    Tagilla,
    TagillaAgro,
    BossTest,

    Obdolbs,
    ExUsec,
    BigPipe,
    BirdEye,
    FollowerBully,
    FollowerGluharAssault,
    FollowerGluharProtect,
    FollowerGluharScout,
    FollowerKojaniy,
    FollowerSanitar,
    FlBoar,
    FlBoarCl,
    FlBoarSt,
    FlKlnAslt,
    KolonSec,
    TagillaFollower,
    HelperAgro,

    Gifter,
    Killa,
    KillaAgro,
    Marksman,
    BoarSniper,
    PMC,
    SectantPriest,
    SctPredvst,
    PrizrakSt,
    Oni,
    SectantWarrior,
    CursAssault,
    Assault,
    PmcBear,
    PmcUsec,
    InfectedSlow,
}
